// Generated by Wrangler on Tue Jun 04 2024 14:29:29 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	// BROWSER: Fetcher;
	AI: Ai
}
